# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='private.proto',
  package='entrypoint',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rprivate.proto\x12\nentrypoint\"\xfe\x05\n\tEtlOutput\x12\x13\n\x0bmean_radius\x18\x01 \x01(\x02\x12\x14\n\x0cmean_texture\x18\x02 \x01(\x02\x12\x16\n\x0emean_perimeter\x18\x03 \x01(\x02\x12\x11\n\tmean_area\x18\x04 \x01(\x02\x12\x17\n\x0fmean_smoothness\x18\x05 \x01(\x02\x12\x18\n\x10mean_compactness\x18\x06 \x01(\x02\x12\x16\n\x0emean_concavity\x18\x07 \x01(\x02\x12\x1b\n\x13mean_concave_points\x18\x08 \x01(\x02\x12\x15\n\rmean_symmetry\x18\t \x01(\x02\x12\x1e\n\x16mean_fractal_dimension\x18\n \x01(\x02\x12\x14\n\x0cradius_error\x18\x0b \x01(\x02\x12\x15\n\rtexture_error\x18\x0c \x01(\x02\x12\x17\n\x0fperimeter_error\x18\r \x01(\x02\x12\x12\n\narea_error\x18\x0e \x01(\x02\x12\x18\n\x10smoothness_error\x18\x0f \x01(\x02\x12\x19\n\x11\x63ompactness_error\x18\x10 \x01(\x02\x12\x17\n\x0f\x63oncavity_error\x18\x11 \x01(\x02\x12\x1c\n\x14\x63oncave_points_error\x18\x12 \x01(\x02\x12\x16\n\x0esymmetry_error\x18\x13 \x01(\x02\x12\x1f\n\x17\x66ractal_dimension_error\x18\x14 \x01(\x02\x12\x14\n\x0cworst_radius\x18\x15 \x01(\x02\x12\x15\n\rworst_texture\x18\x16 \x01(\x02\x12\x17\n\x0fworst_perimeter\x18\x17 \x01(\x02\x12\x12\n\nworst_area\x18\x18 \x01(\x02\x12\x18\n\x10worst_smoothness\x18\x19 \x01(\x02\x12\x19\n\x11worst_compactness\x18\x1a \x01(\x02\x12\x17\n\x0fworst_concavity\x18\x1b \x01(\x02\x12\x1c\n\x14worst_concave_points\x18\x1c \x01(\x02\x12\x16\n\x0eworst_symmetry\x18\x1d \x01(\x02\x12\x1f\n\x17worst_fractal_dimension\x18\x1e \x01(\x02\"4\n\x0bModelOutput\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\x08\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x62\x06proto3')
)




_ETLOUTPUT = _descriptor.Descriptor(
  name='EtlOutput',
  full_name='entrypoint.EtlOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean_radius', full_name='entrypoint.EtlOutput.mean_radius', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_texture', full_name='entrypoint.EtlOutput.mean_texture', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_perimeter', full_name='entrypoint.EtlOutput.mean_perimeter', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_area', full_name='entrypoint.EtlOutput.mean_area', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_smoothness', full_name='entrypoint.EtlOutput.mean_smoothness', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_compactness', full_name='entrypoint.EtlOutput.mean_compactness', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_concavity', full_name='entrypoint.EtlOutput.mean_concavity', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_concave_points', full_name='entrypoint.EtlOutput.mean_concave_points', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_symmetry', full_name='entrypoint.EtlOutput.mean_symmetry', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_fractal_dimension', full_name='entrypoint.EtlOutput.mean_fractal_dimension', index=9,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius_error', full_name='entrypoint.EtlOutput.radius_error', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='texture_error', full_name='entrypoint.EtlOutput.texture_error', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='perimeter_error', full_name='entrypoint.EtlOutput.perimeter_error', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area_error', full_name='entrypoint.EtlOutput.area_error', index=13,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='smoothness_error', full_name='entrypoint.EtlOutput.smoothness_error', index=14,
      number=15, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compactness_error', full_name='entrypoint.EtlOutput.compactness_error', index=15,
      number=16, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concavity_error', full_name='entrypoint.EtlOutput.concavity_error', index=16,
      number=17, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concave_points_error', full_name='entrypoint.EtlOutput.concave_points_error', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symmetry_error', full_name='entrypoint.EtlOutput.symmetry_error', index=18,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fractal_dimension_error', full_name='entrypoint.EtlOutput.fractal_dimension_error', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_radius', full_name='entrypoint.EtlOutput.worst_radius', index=20,
      number=21, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_texture', full_name='entrypoint.EtlOutput.worst_texture', index=21,
      number=22, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_perimeter', full_name='entrypoint.EtlOutput.worst_perimeter', index=22,
      number=23, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_area', full_name='entrypoint.EtlOutput.worst_area', index=23,
      number=24, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_smoothness', full_name='entrypoint.EtlOutput.worst_smoothness', index=24,
      number=25, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_compactness', full_name='entrypoint.EtlOutput.worst_compactness', index=25,
      number=26, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_concavity', full_name='entrypoint.EtlOutput.worst_concavity', index=26,
      number=27, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_concave_points', full_name='entrypoint.EtlOutput.worst_concave_points', index=27,
      number=28, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_symmetry', full_name='entrypoint.EtlOutput.worst_symmetry', index=28,
      number=29, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worst_fractal_dimension', full_name='entrypoint.EtlOutput.worst_fractal_dimension', index=29,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=796,
)


_MODELOUTPUT = _descriptor.Descriptor(
  name='ModelOutput',
  full_name='entrypoint.ModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='entrypoint.ModelOutput.category', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='entrypoint.ModelOutput.probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=798,
  serialized_end=850,
)

DESCRIPTOR.message_types_by_name['EtlOutput'] = _ETLOUTPUT
DESCRIPTOR.message_types_by_name['ModelOutput'] = _MODELOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EtlOutput = _reflection.GeneratedProtocolMessageType('EtlOutput', (_message.Message,), dict(
  DESCRIPTOR = _ETLOUTPUT,
  __module__ = 'private_pb2'
  # @@protoc_insertion_point(class_scope:entrypoint.EtlOutput)
  ))
_sym_db.RegisterMessage(EtlOutput)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), dict(
  DESCRIPTOR = _MODELOUTPUT,
  __module__ = 'private_pb2'
  # @@protoc_insertion_point(class_scope:entrypoint.ModelOutput)
  ))
_sym_db.RegisterMessage(ModelOutput)


# @@protoc_insertion_point(module_scope)
