# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "pip"
    target-branch: "main"
    # Look for a `Pipfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "data-science"
      - "dependencies"
    # Add reviewers
    reviewers:
      - "konstellation-io/data-scientists"

  # Enable updates for Github Actions
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
    labels:
      - "ci-cd"
      - "dependencies"
    # Add reviewers
    reviewers:
      - "konstellation-io/devops"
