# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: private.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import public_input_pb2 as public__input__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='private.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rprivate.proto\x1a\x12public_input.proto\"r\n\tEtlOutput\x12\x31\n\x0einput_features\x18\x01 \x01(\x0b\x32\x19.entrypoint.InputFeatures\x12\x32\n\x0fscaled_features\x18\x02 \x01(\x0b\x32\x19.entrypoint.InputFeatures\"4\n\x0bModelOutput\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\x08\x12\x13\n\x0bprobability\x18\x02 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[public__input__pb2.DESCRIPTOR,])




_ETLOUTPUT = _descriptor.Descriptor(
  name='EtlOutput',
  full_name='EtlOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_features', full_name='EtlOutput.input_features', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scaled_features', full_name='EtlOutput.scaled_features', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=151,
)


_MODELOUTPUT = _descriptor.Descriptor(
  name='ModelOutput',
  full_name='ModelOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='ModelOutput.category', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='probability', full_name='ModelOutput.probability', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=205,
)

_ETLOUTPUT.fields_by_name['input_features'].message_type = public__input__pb2._INPUTFEATURES
_ETLOUTPUT.fields_by_name['scaled_features'].message_type = public__input__pb2._INPUTFEATURES
DESCRIPTOR.message_types_by_name['EtlOutput'] = _ETLOUTPUT
DESCRIPTOR.message_types_by_name['ModelOutput'] = _MODELOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EtlOutput = _reflection.GeneratedProtocolMessageType('EtlOutput', (_message.Message,), dict(
  DESCRIPTOR = _ETLOUTPUT,
  __module__ = 'private_pb2'
  # @@protoc_insertion_point(class_scope:EtlOutput)
  ))
_sym_db.RegisterMessage(EtlOutput)

ModelOutput = _reflection.GeneratedProtocolMessageType('ModelOutput', (_message.Message,), dict(
  DESCRIPTOR = _MODELOUTPUT,
  __module__ = 'private_pb2'
  # @@protoc_insertion_point(class_scope:ModelOutput)
  ))
_sym_db.RegisterMessage(ModelOutput)


# @@protoc_insertion_point(module_scope)
